server:
  port: 8080

spring:
  application:
    name: deliverytech
  datasource:
    url: jdbc:h2:mem:deliverydb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        jdbc:
          '[batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
    open-in-view: false
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: ${ACTUATOR_PASSWORD} 
      roles: ACTUATOR_ADMIN
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  tracing:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    '[org.springframework.data.redis]': TRACE
    '[com.delivery_api.service.impl]': DEBUG